"""data2.1

Revision ID: bb6266f4ce2d
Revises: 
Create Date: 2024-07-29 14:27:45.198268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bb6266f4ce2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    op.drop_column('tasks', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.drop_column('tasks', 'task_id')
    # ### end Alembic commands ###
